---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars:
    terraform_version: 0.14.6
  tasks:
    - name: Install the dependencies
      ansible.builtin.package:
        name:
          - wget
          - git
        state: present
    - name: Installing AWS-CLI 2.x
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        ./aws/install -i /usr/local/aws-cli -b /usr/local/bin --update
        ln -nsf /usr/local/bin/aws /usr/bin/aws
        rm -rf awscliv2.zip
    - name: Downloading Terraform package
      command: wget https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
      retries: 6
      delay: 30
      register: result
      until: result.rc == 0
    - name: Installing Terraform
      shell: |
        unzip terraform_{{ terraform_version }}_linux_amd64.zip
        mv terraform /usr/bin/
        rm -rf terraform_{{ terraform_version }}_linux_amd64.zip
    - name: Install aws-iam-authenticator
      shell: "{{ item }}"
      with_items:
        - curl -o aws-iam-authenticator https://s3.us-west-2.amazonaws.com/amazon-eks/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator
        - chmod +x ./aws-iam-authenticator
        - mkdir -p $HOME/bin && cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$PATH:$HOME/bin
        - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
        - mv aws-iam-authenticator /usr/bin/
    - name: Install kubectl
      shell: |
        curl -sLO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        ln -s /usr/local/bin/kubectl /usr/bin/kubectl
    - name: Install helm
      shell: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
    - name: Install eksctl
      shell: |
        curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bin